### ISSUE TITLE
Running plain Popper models does not work

### ISSUE THREAD

**Issue by hakank** [celinehocquette/magicpopper#2]
After fixing the error reporting in #1 (commenting the lines regarding args.info in utils.py), the MagicPopper specific examples works, but for the plain Popper examples errors are thrown. 

```
$ python3 popper.py examples/alleven       
Traceback (most recent call last):
  File "popper.py", line 7, in <module>
    settings = Settings()
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/util.py", line 447, in __init__
    self.logger.debug(f'Max vars: {self.max_vars}')
AttributeError: 'Settings' object has no attribute 'max_vars'
```

After commenting the offending line and the next line (since it yields a similar error):
```
   # self.logger.debug(f'Max vars: {self.max_vars}')
   # self.logger.debug(f'Max body: {self.max_body}')
```

then the program throws this error:
```
Traceback (most recent call last):
  File "popper.py", line 8, in <module>
    prog, score, stats = learn_solution(settings)
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/loop.py", line 316, in learn_solution
    timeout(settings, popper, (settings,), timeout_duration=int(settings.timeout),)
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/util.py", line 78, in timeout
    raise moo
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/util.py", line 70, in timeout
    result = func(*args, **kwargs)
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/loop.py", line 67, in popper
    generator = Generator(settings, grounder)
  File "/home/hakank/inductive_programming/andrewcropper/popper/magicpopper/magicpopper/popper/generate.py", line 40, in __init__
    encoding.append(f'max_body({settings.max_body}).')
AttributeError: 'Settings' object has no attribute 'max_body'
```

**Comment by celinehocquette** [comment]
Thanks for pointing this issue out, I have fixed the default value issue for max_vars and max_body.

**Comment by hakank** [comment]
Thanks. I can confirm that it now works.
